version: 2

jobs:
    build:
      machine: true
      steps:
        - checkout
        - run: wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo mv ~/project/nextflow /usr/local/bin/ ; sudo apt-get install graphviz
        - run: cd ~ && git clone --depth=1 https://github.com/IARCbioinfo/data_test.git
        - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
        - run: cd ~/project/ ; docker build -t iarcbioinfo/qualimap-nf .
        - run: cd ; nextflow run ~/project/Qualimap.nf --help
        - run: cd ; nextflow run ~/project/Qualimap.nf -with-docker iarcbioinfo/qualimap-nf --input_folder ~/data_test/BAM/ --output_folder ~/results/ --output_format pdf --mem 7
        - run: cd ; mv ~/results/nf-pipeline_info/Qualimap_dag.html ~/project/
        - deploy:
            branch: [dev, master]
            command: chmod +x deploy.sh && ./deploy.sh
